name: encplus
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  firebase_auth: ^4.4.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  file_picker: ^5.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
